# Generated by Django 4.1.1 on 2022-09-06 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locations',
            options={'ordering': ('category',)},
        ),
    ]
