# Generated by Django 4.1.1 on 2022-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedback_traveldesk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveldesk',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
