# Generated by Django 4.1.1 on 2022-09-12 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_locations_created_locations_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to='images/2022-09-12 16:16:04.759984'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 16, 16, 4, 757176)),
        ),
    ]
