# Generated by Django 4.1.1 on 2022-09-12 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_feedback_image_alter_locations_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to='images/2022-09-12 23:05:15.261536__'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 23, 5, 15, 258343)),
        ),
    ]
