# Generated by Django 4.1.1 on 2022-09-14 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_feedback_image_alter_locations_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date_generated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='traveldesk',
            old_name='date_generated',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='feedback',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='traveldesk',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to='images/2022-09-14 16:03:35.930643__'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 16, 3, 35, 927645)),
        ),
    ]
